require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NovelLinksController do

  # This should return the minimal set of attributes required to create a valid
  # NovelLink. As you add validations to NovelLink, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "page" => "" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NovelLinksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all novel_links as @novel_links" do
      novel_link = NovelLink.create! valid_attributes
      get :index, {}, valid_session
      assigns(:novel_links).should eq([novel_link])
    end
  end

  describe "GET show" do
    it "assigns the requested novel_link as @novel_link" do
      novel_link = NovelLink.create! valid_attributes
      get :show, {:id => novel_link.to_param}, valid_session
      assigns(:novel_link).should eq(novel_link)
    end
  end

  describe "GET new" do
    it "assigns a new novel_link as @novel_link" do
      get :new, {}, valid_session
      assigns(:novel_link).should be_a_new(NovelLink)
    end
  end

  describe "GET edit" do
    it "assigns the requested novel_link as @novel_link" do
      novel_link = NovelLink.create! valid_attributes
      get :edit, {:id => novel_link.to_param}, valid_session
      assigns(:novel_link).should eq(novel_link)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NovelLink" do
        expect {
          post :create, {:novel_link => valid_attributes}, valid_session
        }.to change(NovelLink, :count).by(1)
      end

      it "assigns a newly created novel_link as @novel_link" do
        post :create, {:novel_link => valid_attributes}, valid_session
        assigns(:novel_link).should be_a(NovelLink)
        assigns(:novel_link).should be_persisted
      end

      it "redirects to the created novel_link" do
        post :create, {:novel_link => valid_attributes}, valid_session
        response.should redirect_to(NovelLink.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved novel_link as @novel_link" do
        # Trigger the behavior that occurs when invalid params are submitted
        NovelLink.any_instance.stub(:save).and_return(false)
        post :create, {:novel_link => { "page" => "invalid value" }}, valid_session
        assigns(:novel_link).should be_a_new(NovelLink)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NovelLink.any_instance.stub(:save).and_return(false)
        post :create, {:novel_link => { "page" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested novel_link" do
        novel_link = NovelLink.create! valid_attributes
        # Assuming there are no other novel_links in the database, this
        # specifies that the NovelLink created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        NovelLink.any_instance.should_receive(:update).with({ "page" => "" })
        put :update, {:id => novel_link.to_param, :novel_link => { "page" => "" }}, valid_session
      end

      it "assigns the requested novel_link as @novel_link" do
        novel_link = NovelLink.create! valid_attributes
        put :update, {:id => novel_link.to_param, :novel_link => valid_attributes}, valid_session
        assigns(:novel_link).should eq(novel_link)
      end

      it "redirects to the novel_link" do
        novel_link = NovelLink.create! valid_attributes
        put :update, {:id => novel_link.to_param, :novel_link => valid_attributes}, valid_session
        response.should redirect_to(novel_link)
      end
    end

    describe "with invalid params" do
      it "assigns the novel_link as @novel_link" do
        novel_link = NovelLink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NovelLink.any_instance.stub(:save).and_return(false)
        put :update, {:id => novel_link.to_param, :novel_link => { "page" => "invalid value" }}, valid_session
        assigns(:novel_link).should eq(novel_link)
      end

      it "re-renders the 'edit' template" do
        novel_link = NovelLink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NovelLink.any_instance.stub(:save).and_return(false)
        put :update, {:id => novel_link.to_param, :novel_link => { "page" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested novel_link" do
      novel_link = NovelLink.create! valid_attributes
      expect {
        delete :destroy, {:id => novel_link.to_param}, valid_session
      }.to change(NovelLink, :count).by(-1)
    end

    it "redirects to the novel_links list" do
      novel_link = NovelLink.create! valid_attributes
      delete :destroy, {:id => novel_link.to_param}, valid_session
      response.should redirect_to(novel_links_url)
    end
  end

end
